# Generated by Django 4.2.11 on 2025-10-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=255)),
                ("fecha", models.DateTimeField()),
                ("lugar", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PROGRAMADO", "Programado"),
                            ("CERRADO", "Cerrado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        db_index=True,
                        default="PROGRAMADO",
                        max_length=20,
                    ),
                ),
                ("cupo_total", models.PositiveIntegerField(blank=True, null=True)),
                ("cupo_disponible", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-fecha",),
                "indexes": [
                    models.Index(fields=["fecha"], name="partido_fecha_idx"),
                    models.Index(fields=["estado"], name="partido_estado_idx"),
                ],
            },
        ),
    ]
