# Generated by Django 4.2.11 on 2026-01-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partidos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partido",
            name="habilitado",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="partido",
            name="solo_socios",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
