# Generated by Django 5.1 on 2025-10-21 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("filiales", "0002_initial"),
        ("foro", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="respuesta",
            name="autor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respuestas_creadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="respuesta",
            name="respuesta_padre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respuestas_hijas",
                to="foro.respuesta",
            ),
        ),
        migrations.AddField(
            model_name="tema",
            name="autor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="temas_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tema",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="temas",
                to="foro.categoria",
            ),
        ),
        migrations.AddField(
            model_name="tema",
            name="filial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="temas",
                to="filiales.filial",
            ),
        ),
        migrations.AddField(
            model_name="respuesta",
            name="tema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respuestas",
                to="foro.tema",
            ),
        ),
    ]
