# Generated by Django 4.2.11 on 2025-10-28 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("filiales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Accion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recurso", models.CharField(max_length=150)),
                ("recurso_id", models.CharField(max_length=50)),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("CREAR", "Crear"),
                            ("ACTUALIZAR", "Actualizar"),
                            ("ELIMINAR", "Eliminar"),
                            ("APROBAR", "Aprobar"),
                            ("RECHAZAR", "Rechazar"),
                            ("SUSPENDER", "Suspender"),
                            ("HABILITAR", "Habilitar"),
                            ("DESHABILITAR", "Deshabilitar"),
                            ("CAMBIAR_AUTORIDAD", "Cambiar autoridad"),
                            ("ASIGNAR_ENTRADAS", "Asignar entradas"),
                        ],
                        max_length=40,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                (
                    "filial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acciones",
                        to="filiales.filial",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["accion"], name="accion_tipo_idx"),
                    models.Index(
                        fields=["recurso", "recurso_id"], name="accion_recurso_idx"
                    ),
                    models.Index(fields=["usuario"], name="accion_usuario_idx"),
                    models.Index(fields=["filial"], name="accion_filial_idx"),
                ],
            },
        ),
    ]
