# Generated by Django 4.2.11 on 2025-10-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accion",
            name="user_agent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
