version: "3.9"

services:
  web:
    build: ..
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    env_file:
      - ../.env
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: filiales
      POSTGRES_USER: filiales
      POSTGRES_PASSWORD: filiales
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
volumes:
  pgdata:
