# Generated by Django 4.2.11 on 2025-10-28 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("filiales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("asunto", models.CharField(max_length=255)),
                (
                    "visibilidad",
                    models.CharField(
                        choices=[("FILIAL", "Filial"), ("GLOBAL", "Global")],
                        default="FILIAL",
                        max_length=10,
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversaciones_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversaciones",
                        to="filiales.filial",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Mensaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("texto", models.TextField()),
                (
                    "conversacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes",
                        to="mensajes.conversacion",
                    ),
                ),
                (
                    "emisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mensajes_enviados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leido_por",
                    models.ManyToManyField(
                        blank=True,
                        related_name="mensajes_leidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "indexes": [
                    models.Index(
                        fields=["conversacion"], name="mensaje_conversacion_idx"
                    ),
                    models.Index(fields=["emisor"], name="mensaje_emisor_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="conversacion",
            index=models.Index(
                fields=["visibilidad"], name="conversacion_visibilidad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversacion",
            index=models.Index(fields=["filial"], name="conversacion_filial_idx"),
        ),
    ]
