# Generated by Django 4.2.11 on 2026-01-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuario",
            name="es_socio",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="numero_socio",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
