# Generated by Django 4.2.11 on 2025-10-28 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("filiales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                            ("ENTREGADO", "Entregado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        db_index=True,
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos",
                        to="filiales.filial",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255)),
                ("sku", models.CharField(max_length=40, unique=True)),
                ("categoria", models.CharField(max_length=120)),
                ("unidad", models.CharField(max_length=50)),
                ("descripcion", models.TextField(blank=True)),
                ("activo", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "ordering": ("nombre",),
                "indexes": [
                    models.Index(fields=["sku"], name="producto_sku_idx"),
                    models.Index(fields=["categoria"], name="producto_categoria_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PedidoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cantidad", models.PositiveIntegerField()),
                ("detalle", models.TextField(blank=True)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pedidos.pedido",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedido_items",
                        to="pedidos.producto",
                    ),
                ),
            ],
            options={
                "ordering": ("producto__nombre",),
                "indexes": [
                    models.Index(fields=["pedido"], name="pedido_item_pedido_idx"),
                    models.Index(fields=["producto"], name="pedido_item_producto_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="pedido",
            index=models.Index(fields=["estado"], name="pedido_estado_idx"),
        ),
        migrations.AddIndex(
            model_name="pedido",
            index=models.Index(
                fields=["filial", "estado"], name="pedido_filial_estado_idx"
            ),
        ),
    ]
