# Generated by Django 4.2.11 on 2025-10-28 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Filial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255)),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("activa", models.BooleanField(db_index=True, default=True)),
                ("direccion", models.CharField(blank=True, max_length=255)),
                ("ciudad", models.CharField(max_length=120)),
                ("provincia", models.CharField(max_length=120)),
                ("pais", models.CharField(default="Argentina", max_length=120)),
                ("contacto_email", models.EmailField(blank=True, max_length=254)),
                ("contacto_telefono", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "ordering": ("nombre",),
                "indexes": [
                    models.Index(fields=["activa"], name="filial_activa_idx"),
                    models.Index(fields=["codigo"], name="filial_codigo_idx"),
                    models.Index(
                        fields=["ciudad", "provincia"], name="filial_ciudad_prov_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Autoridad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cargo",
                    models.CharField(
                        choices=[
                            ("PRESIDENTE", "Presidente"),
                            ("SECRETARIO", "Secretario"),
                            ("TESORERO", "Tesorero"),
                            ("VOCAL", "Vocal"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("persona_nombre", models.CharField(max_length=255)),
                ("persona_documento", models.CharField(max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=50)),
                ("desde", models.DateField()),
                ("hasta", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField(db_index=True, default=True)),
                (
                    "filial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autoridades",
                        to="filiales.filial",
                    ),
                ),
            ],
            options={
                "ordering": ("-activo", "cargo"),
                "indexes": [
                    models.Index(
                        fields=["filial", "activo"], name="autoridad_filial_activo_idx"
                    )
                ],
            },
        ),
    ]
