# Generated by Django 5.1 on 2025-10-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('direccion', models.CharField(max_length=255, verbose_name='dirección')),
                ('ciudad', models.CharField(max_length=120, verbose_name='ciudad')),
                ('provincia', models.CharField(max_length=120, verbose_name='provincia')),
                ('pais', models.CharField(default='Argentina', max_length=120, verbose_name='país')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitud')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='fecha de creación')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('SUSPENDIDA', 'Suspendida')], default='ACTIVA', max_length=15, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiales',
                'ordering': ('nombre',),
            },
        ),
    ]
