# Generated by Django 4.2.11 on 2026-01-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="autoridad",
            name="es_socio",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Es socio del club"
            ),
        ),
        migrations.AddField(
            model_name="autoridad",
            name="numero_socio",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Número de socio"
            ),
        ),
    ]
