# Generated by Django 4.2.11 on 2025-10-28 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("filiales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccionSolidaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                ("fecha", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PROGRAMADA", "Programada"),
                            ("EN_CURSO", "En curso"),
                            ("FINALIZADA", "Finalizada"),
                        ],
                        default="PROGRAMADA",
                        max_length=20,
                    ),
                ),
                ("ubicacion", models.CharField(blank=True, max_length=255)),
                ("participantes", models.PositiveIntegerField(default=0)),
                (
                    "imagen_principal",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="acciones/principal/",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acciones_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acciones_solidarias",
                        to="filiales.filial",
                    ),
                ),
            ],
            options={
                "ordering": ("-fecha", "-created_at"),
                "indexes": [
                    models.Index(fields=["estado"], name="accion_estado_idx"),
                    models.Index(fields=["fecha"], name="accion_fecha_idx"),
                    models.Index(
                        fields=["filial", "fecha"], name="accion_filial_fecha_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AccionImagen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("imagen", models.ImageField(upload_to="acciones/imagenes/")),
                ("es_principal", models.BooleanField(default=False)),
                (
                    "accion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="acciones.accionsolidaria",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["accion"], name="accion_imagen_accion_idx")
                ],
            },
        ),
    ]
