# Generated by Django 5.1 on 2025-10-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="título")),
                ("descripcion", models.TextField(verbose_name="descripción")),
                ("fecha", models.DateField(verbose_name="fecha")),
                (
                    "estado",
                    models.CharField(
                        choices=[("BORRADOR", "Borrador"), ("PUBLICADA", "Publicada")],
                        default="BORRADOR",
                        max_length=15,
                        verbose_name="estado",
                    ),
                ),
                (
                    "creada",
                    models.DateTimeField(auto_now_add=True, verbose_name="creada"),
                ),
                (
                    "actualizada",
                    models.DateTimeField(auto_now=True, verbose_name="actualizada"),
                ),
            ],
            options={
                "verbose_name": "Acción",
                "verbose_name_plural": "Acciones",
                "ordering": ("-fecha",),
            },
        ),
        migrations.CreateModel(
            name="AccionImagen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(upload_to="acciones", verbose_name="imagen"),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="descripción"
                    ),
                ),
                (
                    "creada",
                    models.DateTimeField(auto_now_add=True, verbose_name="creada"),
                ),
            ],
            options={
                "verbose_name": "Imagen de acción",
                "verbose_name_plural": "Imágenes de acciones",
            },
        ),
    ]
