# Generated by Django 5.1 on 2025-10-21 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("acciones", "0001_initial"),
        ("filiales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accion",
            name="creador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acciones_creadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accion",
            name="filial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acciones",
                to="filiales.filial",
            ),
        ),
        migrations.AddField(
            model_name="accionimagen",
            name="accion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imagenes",
                to="acciones.accion",
            ),
        ),
    ]
