# Generated by Django 5.1 on 2025-10-21 20:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SolicitudEntrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_solicitada",
                    models.PositiveIntegerField(verbose_name="cantidad solicitada"),
                ),
                (
                    "cantidad_aprobada",
                    models.PositiveIntegerField(
                        default=0, verbose_name="cantidad aprobada"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APROBADA", "Aprobada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                        verbose_name="estado",
                    ),
                ),
                ("motivo", models.TextField(blank=True, verbose_name="motivo")),
                (
                    "fecha_solicitud",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="fecha de solicitud",
                    ),
                ),
                (
                    "fecha_resolucion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de resolución"
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de entrada",
                "verbose_name_plural": "Solicitudes de entradas",
                "ordering": ("-fecha_solicitud",),
            },
        ),
    ]
