# Generated by Django 5.1 on 2025-10-21 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entradas", "0001_initial"),
        ("filiales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudentrada",
            name="filial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solicitudes_entradas",
                to="filiales.filial",
            ),
        ),
    ]
