# Generated by Django 5.1 on 2025-10-21 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entradas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudentrada',
            name='resolvio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_resueltas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudentrada',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_realizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
